### ISSUE TITLE
Modularização

### ISSUE THREAD

**Issue by peidrao** [0x67757300/uHTTP#2]
Parabéns pelo projeto, a ideia é fascinante. Sugiro considerar uma modularização dos arquivos, distribuindo as responsabilidades em vez de centralizá-las exclusivamente em [**uhttp.py**](https://github.com/0x67757300/uHTTP/blob/main/uhttp.py).

**Comment by 0x67757300** [comment]
Muito obrigado!

A ideia é funcionar como o [Bottle](https://bottlepy.org/docs/dev/), visando a portabilidade. Por isso também me restringi a não usar módulos externos.

Por exemplo, para começar um projeto com o µHTTP basta copiar o arquivo `uhttp.py`.
